### ISSUE TITLE
Updating documentation to reflect that now macOs 13.5 is needed

### ISSUE THREAD

**Issue by nahakiole** [mustafaaljadery/mlxserver#3]
![CleanShot 2024-03-15 at 08 05 09](https://github.com/mustafaaljadery/mlxserver/assets/4542479/214474cb-9d55-42e8-9f39-6d3da0ee50db)

Currently on getting started it's written that macOs 13.3 is needed, but when installing it requires 13.5. 

***ImportError: Only macOS 13.5 and newer are supported, not 13.4***

```
Traceback (most recent call last):
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlx/_os_warning.py", line 7, in <module>
    raise ImportError(
ImportError: Only macOS 13.5 and newer are supported, not 13.4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robin/IdeaProjects/robotllm/main.py", line 1, in <module>
    from mlxserver import MLXServer
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlxserver/__init__.py", line 1, in <module>
    from .server import MLXServer
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlxserver/server.py", line 3, in <module>
    from .generate import generate, generate_steps
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlxserver/generate.py", line 1, in <module>
    from mlx_lm.utils import load, generate_step
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlx_lm/__init__.py", line 3, in <module>
    from .utils import convert, generate, load
  File "/Users/robin/opt/miniconda3/envs/robotllm/lib/python3.11/site-packages/mlx_lm/utils.py", line 14, in <module>
    import mlx.core as mx
ImportError: initialization failed
Execution time: 0,12s
```

**Comment by mustafaaljadery** [comment]
Resolving right now. Thanks for highlighting!

**Comment by mustafaaljadery** [comment]
Fixed!
